Allow to bypass gitleaks
Signed-off-by: Lunik <lunik@tiwabbit.fr>

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -4,10 +4,12 @@
 ## LEAKS ##
 ###########
 
-which gitleaks > /dev/null
-if [ "$?" -eq 0 ]; then
-  gitleaks protect --verbose --staged
-else
-  echo "[INFO] Ignoring 'gitleaks' check because the binary is missing"
-  echo "[INFO] More info https://github.com/zricethezav/gitleaks"
+if [ -z "${GITLEAKS_IGNORE}" ]; then
+  which gitleaks > /dev/null
+  if [ "$?" -eq 0 ]; then
+    gitleaks protect --verbose --staged
+  else
+    echo "[INFO] Ignoring 'gitleaks' check because the binary is missing"
+    echo "[INFO] More info https://github.com/zricethezav/gitleaks"
+  fi
 fi
